### ISSUE TITLE
About Ealsticsearch ppc64le docker image

### ISSUE THREAD

**Issue by oscarzhao** [schabrolles/rear#1]
Sorry to raise a question not related to the topic, because I cannot find a way to get connection with you.  
Recently I'm trying to make docker images on ppc64le architecture, many problems comes out, esp. those which has to be built from source code. One is about elasticsearch, I found one at [schabrolles](https://hub.docker.com/r/schabrolles/elasticsearch_ppc64le/), whose version is <2.0, lacking many new features. However, you must be more expericenced at making images at ppc64le and java language (i'm new to ppc64le, and knows nothing about java and its tools chains), so here I ask for your help.  Thank you.

**Comment by schabrolles** [comment]
Hi @oscarzhao 

It has been a long time since I have played with elasticsearch. Honnestly, I just built it because it was a requirement for grafana (it is not the case anymore).
Elasticsearch used Java... this mean you should not have to rebuild it to make it run on Power (ppc64 or ppc64le). 
I will try to look at it in my spare time

**Comment by schabrolles** [comment]
Hi @oscarzhao 

I have ulploaded a new version of elasticsearch 2.3.3. Tell me if it works
